In [1]:

from src.tools import convert_image_to_array,labels
import numpy as np
import pickle
import cv2
from os import listdir
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.preprocessing import LabelBinarizer
from keras.models import Sequential
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.layers.core import Activation, Flatten, Dropout, Dense
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator
from keras.optimizers import Adam
from keras.preprocessing import image

Using TensorFlow backend.


In [2]:
img = ('../color/Grape/Grape___Black_rot/8eb4a448-b517-4039-b736-9f108157de73___FAM_B.Rot 3596.JPG')

img=convert_image_to_array(img)

In [3]:
loaded_model = pickle.load(open('./output/cnn_model.pkl', 'rb'))
pred = loaded_model.predict(np.expand_dims(img,axis=0))
print(pred)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [4]:
img = ('../color/Grape/Grape___Black_rot/8c2374fd-2ad8-4f94-8634-9adfc9933444___FAM_B.Rot 0543.JPG')

img=convert_image_to_array(img)

loaded_model = pickle.load(open('./output/cnn_model.pkl', 'rb'))
pred = loaded_model.predict(np.expand_dims(img,axis=0))
print(pred)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
img = ('../color/Grape/Grape___Black_rot/9ddfa57d-e31d-43ef-9738-c62b14b71af8___FAM_B.Rot 3407.JPG')

img=convert_image_to_array(img)

loaded_model = pickle.load(open('./output/cnn_model.pkl', 'rb'))
pred = loaded_model.predict(np.expand_dims(img,axis=0))
print(pred)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
img = ('../color/Grape/Grape___Black_rot/9e074d2d-0075-4e9e-9648-2bf0332517df___FAM_B.Rot 3212.JPG')

img=convert_image_to_array(img)

loaded_model = pickle.load(open('./output/cnn_model.pkl', 'rb'))
pred = loaded_model.predict(np.expand_dims(img,axis=0))
print(pred)

[[0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  3.0876599e-10 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00 1.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00
  0.0000000e+00]]
